### ISSUE TITLE
Add to readme.

### ISSUE THREAD

**Issue by EminenceHC** [Slashek/bootstrap-select-rails#12]
Please add a step in the readme to include *= require bootstrap-select in application.css.scss

**Comment by rafaeliga** [comment]
+1

**Comment by Slashek** [comment]
![screen shot 2015-09-21 at 15 50 34](https://cloud.githubusercontent.com/assets/30107/9993516/891d1af2-6078-11e5-85d6-c4415722298f.png)

I believe it's already there? I'm opened to suggestion via PR how to improve it

**Comment by rafaeliga** [comment]
yes, you are right, but looking only the code, you could think that only the js is required.

**Comment by EminenceHC** [comment]
That was my problem, looking at the readme, I thought that only the JS is required.
