### ISSUE TITLE
update rubygems version

### ISSUE THREAD

**Issue by prosanelli** [Slashek/bootstrap-select-rails#16]
hi, thanks for merging my PR, can you please update the rubygems version so i can use it in my gemfile. thanks.

http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

**Comment by BabaninFV** [comment]
+1

**Comment by falegk** [comment]
Hi.
Can you push the last version (1.10.0 #24 ) on https://rubygems.org/gems/bootstrap-select-rails ?

Now we must use the following to get the updated version.
`gem 'bootstrap-select-rails', '~> 1.10.0', git: 'https://github.com/Slashek/bootstrap-select-rails.git'`

Thanks,
Antony F.

**Comment by Startouf** [comment]
Hey, yes even though the new version of the gem is available, it isn't officially release and if not writing the reference to the git in the Gemfile, the system would load version `1.6.3` by default (VS `1.12.1` currently available at the time of writing)

**Comment by 5minpause** [comment]
@Startouf what prevents an official release? Anything someone could help you with?

**Comment by Startouf** [comment]
Sorry I just happened to contribute with a PR, I'm not a maintainer or anything, and I'm not familiar with deployment procedures on rubygems..

**Comment by 5minpause** [comment]
Oh sorry, the contributor badge made me think so.
@Slashek could you take over here?

**Comment by crevete** [comment]
@Slashek Can you please deploy the last version of gem? FYI, the current version bootstrap select is 1.12.2

**Comment by Slashek** [comment]
Done - pushed version [1.12.1](https://rubygems.org/gems/bootstrap-select-rails). apologies for the delay
