### ISSUE TITLE
Select fields don't render when changing page

### ISSUE THREAD

**Issue by shwashbuckle** [Slashek/bootstrap-select-rails#18]
I have a view file that has a successful implementation of a bootstrap-select-rails select field, however when I navigate to another page and then go back to original page the select fields are rendered as normal bootstrap select fields.  If a refresh the page using the browsers refresh button the select fields also refresh and appear correctly as bootstrap-select-rails selects.  

Any ideas how I can force the rendering of the select fields when changing pages?

**Comment by usmanasif** [comment]
Any solutions?

**Comment by Slashek** [comment]
@shwashbuckle I'm sorry but I won't be able to help you - this gem merely loads js/css of bootstrap select
