### ISSUE TITLE
Bug when using multiple + optgroup

### ISSUE THREAD

**Issue by fractalatcarf** [Slashek/bootstrap-select-rails#27]
When you use multiple + optgroup, there is an issue that prevent normal use. 
This bug is fixed in the latest version of the lib. 
Do you plan to update with 1.12.1 shortly ?
Thanks

**Comment by Slashek** [comment]
feel free to submit PR and will be happy to merge it! thanks @fractalatcarf

**Comment by fractalatcarf** [comment]
great idea @Slashek ! Can you add me as member ? Thx

**Comment by Slashek** [comment]
@fractalatcarf closing this issue, as upgrade has been made :)
