### ISSUE TITLE
Update to 1.12.4

### ISSUE THREAD

**Issue by crevete** [Slashek/bootstrap-select-rails#29]
Is it possible to upgrade this source JS to version 1.12.4 ? Thanks

**Comment by ledsun** [comment]
Was this issue fixed?

**Comment by crevete** [comment]
Nope...

**Comment by ledsun** [comment]
Um... I think version 1.12.4 was published already.
https://rubygems.org/gems/bootstrap-select-rails/versions/1.12.4

**Comment by crevete** [comment]
You are right, the author has merged the PR but not closed this issue.

**Comment by Slashek** [comment]
:) that's what I've done :) thx @crevete
