### ISSUE TITLE
version supporting bootstrap 4?

### ISSUE THREAD

**Issue by stan74fr** [Slashek/bootstrap-select-rails#36]
hello there. I am a bit confused. at the time I am writing this comment, version number on the gem mentions 1.12.4 but apparently bootstrap 4 is supported after version 1.13. can we get the 2 in line? currently the select show disabled after gem installation so presumably the updated version to support bootstrap 4 is not yet pushed. Please advise.

**Comment by stan74fr** [comment]
hi guys. I know you are busy. would welcome your opinion though.

**Comment by Slashek** [comment]
fixed by #37
